# Generated by Django 3.1.5 on 2021-01-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='poll',
            new_name='survey',
        ),
    ]
