# Generated by Django 3.1.5 on 2021-01-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210125_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
